name: Daily Notifications Cron

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  send-daily-notifications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send Daily Notifications
      run: |
        echo "🔔 Triggering daily notifications..."
        
        # Get the current hour for logging
        CURRENT_HOUR=$(date +%H)
        echo "⏰ Current hour: $CURRENT_HOUR"
        
        # Make the API call to trigger daily notifications
        RESPONSE=$(curl -s -X POST \
          "https://hrznuhcwdjnpasfnqqwp.supabase.co/functions/v1/daily-notifications" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}')
        
        echo "📧 Response: $RESPONSE"
        
        # Parse the response to check if it was successful
        SUCCESS=$(echo $RESPONSE | jq -r '.success // false')
        NOTIFICATIONS_SENT=$(echo $RESPONSE | jq -r '.notifications_sent // 0')
        ERRORS=$(echo $RESPONSE | jq -r '.errors // 0')
        
        if [ "$SUCCESS" = "true" ]; then
          echo "✅ Daily notifications sent successfully!"
          echo "📊 Notifications sent: $NOTIFICATIONS_SENT"
          echo "❌ Errors: $ERRORS"
        else
          echo "❌ Failed to send daily notifications"
          echo "📄 Full response: $RESPONSE"
          exit 1
        fi
        
    - name: Log Results
      if: always()
      run: |
        echo "🕐 Cron job completed at $(date)"
        echo "📊 Summary:"
        echo "  - Notifications sent: $NOTIFICATIONS_SENT"
        echo "  - Errors: $ERRORS"
        echo "  - Success: $SUCCESS"















